Визоры
Lemirda/space-station-14 pull request #103
Opened 2024-05-14 14:27 UTC by Evrozor

## Описание PR

Добавлен медицинский хим визор, добавлено исследование "Окулярная технология", добавлен рецепт мед визора и рации. 
Теперь для создания окуляров требуется соответствующее исследование.
**Медиа**

**Проверки**

- [ ] Подойти к исследовательской консоли
- [ ] Вставить диск с очками в сервер
- [ ] Создать техфаб сб, техфаб мед, протолат и автолат
- [ ] Убедиться, что в автолате есть рация
- [ ] Убедиться, что в техфабе сб, техфабе мед и протолате нет сб визора, медицинского визора и очков химического анализа
- [ ] В консоли изучить зеленую ветку вплоть до изучения окулярной технологии
- [ ] Убедиться, что в техфабе сб, техфабе мед и протолате есть сб визор, медицинский визор и очки химического анализа соответственно
- [ ] Заспавнить рацию, и оценочный инструмент. Проверить, что стоимость рации 40.
- [ ] Заспавнить мед визор, очки химического анализа, моток лв проводов, два конденсатора и рацию и поместить все в рюкзак.
- [ ] В меню крафта (G) в разделе одежда, найти рецепт Медицинского хим визора, посмотреть на него и создать предмет.

**Изменения для игроков**

:cl: Evrozor
add:
-  Добавленно новое исследование "окулярная технология" в ветку обслуживания персонала.
-  Добавлен рецепт медицинского визора в Медицинский ТехФаб.
-  Добавлен медицинский хим визор, а также его рецепт в раздел крафта.
-  Добавлен рецепт рации в автолат.
tweak: 
-  Крафт сб и хим визоров, а также хим очков теперь доступен только после изучения окулярной технологии.

**Изменения для разработчиков**

:cl: Evrozor
- Че так муторно пры писать

2024-05-14 18:09 UTC, Lemirda commented
suffix: Андромеда

2024-05-15 16:00 UTC, Lemirda requested changes

2024-05-15 16:00 UTC, Lemirda commented on Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
> +    - type: Tag
A-13 start?

2024-05-15 16:00 UTC, Lemirda commented on Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
> +      - HudChemical
A-13 end?

2024-05-15 16:00 UTC, Lemirda commented on Resources/Prototypes/Entities/Objects/Devices/radio.yml
> +  - type: StaticPrice #A-13 added
тег не отражает краткое содержания изменения в целом как и под ним тоже. В целом как и все остольные.

2024-05-15 16:15 UTC, Lemirda commented
читайте регламент

2024-05-20 18:50 UTC, Lemirda requested changes

2024-05-20 18:50 UTC, Lemirda commented on Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
> +#A-13 for HudChemical craft end
#A-13 HudChemical end

2024-05-20 18:50 UTC, Lemirda commented on Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
> +#A-13 for HudChemical craft start
#A-13 HudChemical start

2024-05-20 18:50 UTC, Lemirda commented on Resources/Prototypes/Entities/Objects/Devices/radio.yml
> +#A-13 added price start
#A-13 Added price for walkie-talkie start

2024-05-20 18:50 UTC, Lemirda commented on Resources/Prototypes/Entities/Objects/Devices/radio.yml
> +#A-13 added price end
#A-13 Added price for walkie-talkie end

2024-05-20 18:50 UTC, Lemirda commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> +      - RadioHandheld #A-13 added for craft MedSolHud
#A-13 Med solution hud

2024-05-20 18:50 UTC, Lemirda commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> +      - ClothingEyesGlassesChemical #A-13 Change (removed from static)
#A-13 HudChemical

2024-05-20 18:50 UTC, Lemirda commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> +      - ClothingEyesHudSecurity #A-13 Change (removed from static)
#A-13 HudSecurity

2024-05-20 18:50 UTC, Lemirda commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> +      - ClothingEyesGlassesChemical #A-13 Change (removed from static)
#A-13 HudChemical

2024-05-20 18:50 UTC, Lemirda commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> +      - ClothingEyesHudMedical #A-13 added for craft MedSolHud
#A-13 HudMedical

2024-05-20 18:50 UTC, Lemirda commented on Resources/Prototypes/tags.yml
> +#A-13 for HudChemical craft start
#A-13 HudMedical start

2024-05-20 18:50 UTC, Lemirda commented on Resources/Prototypes/tags.yml
> +#A-13 for HudChemical craft end
#A-13 HudMedical end

2024-05-20 18:51 UTC, Lemirda commented
Я пометила как надо написать

2024-05-20 18:51 UTC, Lemirda commented
Прочитай пожалуйста и пойми

2024-05-20 18:51 UTC, Lemirda commented
И исправь

2024-05-21 09:47 UTC, Voomra commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> -    - ClothingEyesGlassesChemical
Тут лучше закомментировать с отметкой A-13. В будущем будет понятно, что убрали этот пункт мы

2024-05-21 09:50 UTC, Voomra commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> -      - ClothingEyesHudSecurity
лучше закомментировать с отметкой A-13. В будущем будет понятно, что убрали этот пункт мы

2024-05-21 09:50 UTC, Voomra commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> -      - ClothingEyesGlassesChemical
лучше закомментировать с отметкой A-13. В будущем будет понятно, что убрали этот пункт мы

2024-05-21 09:56 UTC, Voomra commented on Resources/Prototypes/Entities/Objects/Devices/radio.yml
> +  - type: StaticPrice #A-13 added
Для этого есть commit message (название коммита). Метки  А-13 нам нужны для апстримов, чтобы понимать где НАШЕ, а где Чужое. Ну и в целом быстро замечать общие группы изменений.

2024-05-21 10:00 UTC, Evrozor commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> -    - ClothingEyesGlassesChemical
Хорошая идея, хорошо

2024-05-23 16:14 UTC, Lemirda commented
Хуй с ним

2024-05-23 16:14 UTC, Lemirda approved these changes
Леми заеблась

2024-05-23 16:15 UTC, merged