Obmotki
Lemirda/space-station-14 pull request #105
Opened 2024-05-14 18:47 UTC by Waufuf

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения для игроков**

:cl: NezukoDaki
- tweak: Изменены спрайты мед-китам

**Изменения для разработчиков**

:cl:
- add: Добавлены текстуры новых спрайтов
- remove: Убраны старые текстуры
![image](https://github.com/Lemirda/space-station-14/assets/166502778/743008cc-1ef4-4341-9da0-ac456f31704c)

2024-05-15 15:28 UTC, Lemirda commented
very good job

2024-05-15 15:28 UTC, Lemirda commented
![image](https://github.com/Lemirda/space-station-14/assets/142801986/85d5efbc-20c1-4ebe-a18e-a82b2a18e5b9)

2024-05-15 15:28 UTC, Lemirda commented
no. no very good job

2024-05-17 19:30 UTC, Lemirda requested changes

2024-05-17 19:30 UTC, Lemirda commented on Resources/Prototypes/Entities/Objects/Specific/Medical/medkits.yml
> +    sprite: Andromeda/Waufuf/firstaidkits.rsi
Метка #A-13?

2024-05-17 19:30 UTC, Lemirda commented on Resources/Prototypes/Entities/Objects/Specific/Medical/medkits.yml
> +    sprite: Andromeda/Waufuf/firstaidkits.rsi
Метка #A-13?

2024-05-20 19:19 UTC, Waufuf commented
> ## Описание PR
> **Медиа**
> 
> **Проверки**
> 
> * [x]  PR полностью завершён и мне не нужна помощь чтобы его закончить.
> * [x]  Я внимательно просмотрел все свои изменения и багов в них не нашёл.
> * [x]  Я запускал локальный сервер со своими изменениями и всё протестировал.
> * [x]  Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.
> 
> **Изменения для игроков**
> 
> 🆑 NezukoDaki
> 
> * tweak: Изменены спрайты мед-китам
> 
> **Изменения для разработчиков**
> 
> 🆑
> 
> * add: Добавлены текстуры новых спрайтов
> * remove: Убраны старые текстуры
>   ![image](https://private-user-images.githubusercontent.com/166502778/330556828-743008cc-1ef4-4341-9da0-ac456f31704c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMzI1MjYsIm5iZiI6MTcxNjIzMjIyNiwicGF0aCI6Ii8xNjY1MDI3NzgvMzMwNTU2ODI4LTc0MzAwOGNjLTFlZjQtNDM0MS05ZGEwLWFjNDU2ZjMxNzA0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQxOTEwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDExNGY0ZjVlY2JjYjJkMzJmMTI5NjVjMTE4OTgwYWZiNjkxZjAyZjcyNDU3YzBmMWUwOGRmYTJiMjA1MDFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LvsdLS0tyxU7IWrpslPwOsVdxLgi_XvQacrEogtcxTk)

2024-05-20 19:19 UTC, closed without merging