Add files via upload
Lemirda/space-station-14 pull request #27
Opened 2024-04-14 16:13 UTC by Dalexiandr

## Описание PR

**Медиа**

**Проверки**

- [x] Получить исходные данные.
- [x] Сделать фигню и огрести от Лемирды.
- [x] Исправить фигню не полностью и огрести от Лемирды.
- [x] Получить корректировку исходных данных и все исправить, не огребая от Лемирды.

**Изменения для игроков**

:cl: EvilBug
- add: Добавлены 5 новых видов мобов (гопники)
- add: Добавлен перекрашенный в красный рюкзак гопников

**Изменения для разработчиков**

:cl: EvilBug
- add: Добавлен 5 мобов (гопиники) и спрайты красного рюкзака для них же.

2024-04-14 16:15 UTC, Lemirda requested changes
Уберите комментарии, они тут не к чему. Я думаю по названию и так будет понятно что к чему.

2024-04-14 16:18 UTC, Lemirda commented
Измените те так же лицензию в мете

2024-04-14 16:58 UTC, Lemirda commented
Идите к спрайтерам и просите их приделать к модельке в спавне всю одежду(чтоб показывалась вся одежда не нём какая)
В пример возьмите джаггернаута или СПБСТ

2024-04-14 17:13 UTC, Dalexiandr commented
> Идите к спрайтерам и просите их приделать к модельке в спавне всю одежду(чтоб показывалась вся одежда не нём какая) В пример возьмите джаггернаута или СПБСТ

Обратился, ждем.

2024-04-15 19:56 UTC, Dalexiandr commented
> Идите к спрайтерам и просите их приделать к модельке в спавне всю одежду(чтоб показывалась вся одежда не нём какая) В пример возьмите джаггернаута или СПБСТ

Сделано.
Пришлось правда самому кое чего из спрайтов поколдовать.
Мурь мурь готово.

2024-04-19 12:21 UTC, Lemirda approved these changes
Сойдёт

2024-04-19 12:28 UTC, merged