Добавление игральных карт
Lemirda/space-station-14 pull request #38
Opened 2024-04-20 09:30 UTC by Dalexiandr

**Проверки**
- [x] Получить исходные данные и ТЗ.
- [x] Скорректировать исходный код.
- [x] Внести 36 карт, с учетом корректировок и сумок.
- [x] Получить дополнительные спрайты карт.
- [x] Расширить колоду до покерной и прописать ноуспавн, добавить в игромат.
- [x] Решить вопрос с тегами.
- [x] Не быть **нным Лемирдой за косяки в коде.

**Изменения для игроков**
:cl: EvilBug
- add: Добавлены 2 игровые колоды (36 и 54 карт) для игры в дурака и покер с возможностью перетасовки (аналогично ботанической сумке (выкинуть на стол))

**Изменения для разработчиков**
:cl: EvilBug
- add: Чтобы не писать код с 0, пришлось колдовать с поворотом и добавить 2 cs файла для карт из исходников. При проверке, пересобрать сборку.

2024-04-20 13:16 UTC, Lemirda commented
Там всё сделано как надо? Осталось только проверить?

2024-04-20 17:19 UTC, Dalexiandr commented
> Там всё сделано как надо? Осталось только проверить?

Леми, это задача с 2000+ строк кода от новичка с учетом что были перетащены 2 файла с кодом.
У меня оно работает и работает хорошо, я действительно много чего переписал.
Плюс я сделал дополнительно перетасовку и расширил колоду.

Как по факту будет  - нужно смотреть тебе. У меня остается вопрос по тегам и твои предложения по оптимизации кода.
Если что колода привязана к игромату.

2024-04-21 14:28 UTC, Lemirda reviewed
фикс

2024-04-21 14:28 UTC, Lemirda commented on Resources/Locale/ru-RU/Andromeda/playablecards/cards.ftl
> +    .suffix = ИгральныеКарты, Покер
Андромеда, Покерные

2024-04-21 14:28 UTC, Lemirda commented on Resources/Locale/ru-RU/Andromeda/playablecards/cards.ftl
> +    .desc = Колода, созданная для игры в Покер
покер с маленькой

2024-04-21 14:28 UTC, Lemirda commented on Resources/Locale/ru-RU/Andromeda/playablecards/cards.ftl
> +ent-CardBinPoker = колода карт (покер)
покерная колода карт

2024-04-21 14:28 UTC, Lemirda commented on Resources/Locale/ru-RU/Andromeda/playablecards/cards.ftl
> +ent-CardBinFool = колода карт (дурак)
обычная колода карт

2024-04-21 14:28 UTC, Lemirda commented on Resources/Locale/ru-RU/Andromeda/playablecards/cards.ftl
> +    .suffix = ИгральныеКарты, Дурак
Андромеда, Обычные

2024-04-21 14:28 UTC, Lemirda commented on Resources/Locale/ru-RU/Andromeda/playablecards/cards.ftl
> +    .desc = Колода, созданная для игры в Дурака
Колода, созданная для игры в карты.

2024-04-22 23:03 UTC, Dalexiandr commented
> фикс

В общем вот тебе большое обновление, как я и обещал.
Смотри проверяй, баланси.

2024-04-23 18:24 UTC, Dalexiandr commented
Исправил один неприятный баг со стаками, плюс чуть поменял состав набора дилера.
Как говорится, карты деньги, фелинидки.
![image](https://github.com/Lemirda/space-station-14/assets/160354560/6941ddc9-fe34-4d6b-883e-dddc4885075b)

2024-04-25 20:46 UTC, Lemirda approved these changes
Сойдёт

2024-04-27 16:01 UTC, Lemirda requested changes

2024-04-27 16:01 UTC, Lemirda commented on Resources/Prototypes/Andromeda/Evil Prototype's/cardtag.yml
> +- type: Tag
Добавь это просто в cards.yml

2024-04-27 16:01 UTC, Lemirda commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/games.yml
> +    CardBinFool: 3
again tag A-13 card game

2024-04-27 16:01 UTC, Lemirda commented
Жопа конечно там огромная с системой и наворошили то гнездо пиздец как, я сама как ни будь разберусь

2024-04-29 14:42 UTC, Lemirda approved these changes

2024-04-30 10:11 UTC, merged