Правки в ботанику №1 (правки в мутации пшеницы и новая мутация)
Lemirda/space-station-14 pull request #42
Opened 2024-04-20 18:12 UTC by Dalexiandr

**Проверки**
- [ ] Внести правки в таблицу эволюции растений, убрать овес и рис (и так есть в свободном доступе).
- [ ] Добавить в таблицу эволюции растений мясную пшеницу, добавить код, скорректировать спрайты и перевод.
- [ ] Получить подтверждение, что все ок

**Изменения для игроков**
:cl: EvilBug
- add: Добавлена мясная пшеница (получается из мутации обычной пшеницы и непрожареных животных протеинов)
- remove: Из возможных мутаций убраны овес и рис (они уже давно есть в раздатчике семян)

**Изменения для разработчиков**

:cl: EvilBug
- add: В таблицу мутаций пшеницы включена мясная пшеница - мутация проходит при 50 потенции, здоровом растении и добавлении непрожаренных животных протеинов в лоток. Также добавлены спрайты и прописана реакция для получения мяса - нужно скушать пшеницу, внезапно.
- remove: Из таблицы мутаций пшеницы убрана возможность мутировать её в рис и овес, они и так в свободном доступе.

2024-04-21 15:47 UTC, Lemirda requested changes
Не используем ftl

2024-04-21 15:47 UTC, Lemirda commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/hydroponics/seeds.ftl
> +ent-MeatWheatSeeds = пакет семян (мясная пшеница)
Мы не используем ftl, просто пропишите это в самом прототипе.

2024-04-21 15:47 UTC, Lemirda commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/produce.ftl
> +ent-MeatWheatBushel = сноп мясной пшеницы
Тоже самое

2024-04-21 15:47 UTC, Lemirda commented on Resources/Locale/ru-RU/seeds/seeds.ftl
> +seeds-meatwheat-name = мясная пшеница
Тоже самое

2024-04-21 15:47 UTC, Lemirda commented on Resources/Locale/en-US/ss14-ru/prototypes/entities/objects/specific/hydroponics/seeds.ftl
> +ent-MeatWheatSeeds = packet of meatwheat seeds
Тоже самое

2024-04-21 15:47 UTC, Lemirda commented on Resources/Locale/en-US/ss14-ru/prototypes/entities/objects/consumable/food/produce.ftl
> +ent-MeatWheatBushel = meat wheat bushel
Тоже самое

2024-04-21 15:47 UTC, Lemirda commented on Resources/Locale/en-US/seeds/seeds.ftl
> +seeds-meatwheat-name = meatwheat
Тоже самое

2024-04-22 23:02 UTC, Dalexiandr commented
Пупупу... на дворе 2 часа ночки. 
Пойду ка я спатиньки.
Карты я внес, эту хрень уже завтра.

2024-04-23 18:35 UTC, Dalexiandr commented
Доправил локализацию.

2024-04-26 18:45 UTC, Lemirda requested changes

2024-04-26 18:45 UTC, Lemirda commented on Resources/Prototypes/Andromeda/EvilPrototype's/Hydroponics/newseeds.yml
> +  id: MeatWheatSeeds
suffix Андромеда pls

2024-04-26 18:45 UTC, Lemirda commented on Resources/Prototypes/Andromeda/EvilPrototype's/Hydroponics/newseeds.yml
> +  parent: FoodProduceBase
plsss suffix

2024-04-26 18:45 UTC, Lemirda commented on Resources/Prototypes/Hydroponics/seeds.yml
> +    meatwheat:
#A-13 Meet seed ( ну или как то так )

2024-04-27 17:02 UTC, closed without merging