Изменения в ботанику №1 - фикс пшеницы и мясная пшеница
Lemirda/space-station-14 pull request #57
Opened 2024-04-27 17:20 UTC by Dalexiandr

**Проверки**
- [x] Внести правки в таблицу эволюции растений, убрать овес и рис (и так есть в свободном доступе).
- [x] Добавить в таблицу эволюции растений мясную пшеницу, добавить код, скорректировать спрайты и перевод.
- [x] Получить подтверждение, что все ок

**Изменения для игроков**
:cl: EvilBug
- add: Добавлена мясная пшеница (получается из мутации обычной пшеницы и добавления непрожаренных животных протеинов)
- remove: Убрана возможность мутировать пшеницу в рис и овес (итак в свободном доступе).

**Изменения для разработчиков**

:cl: EvilBug
- add: В таблицу мутаций пшеницы включена мясная пшеница - мутация проходит при 50 потенции, здоровом растении и добавлении непрожаренных животных протеинов в лоток. Также добавлены спрайты и прописана реакция для получения мяса - нужно скушать пшеницу, внезапно.
- remove: Из таблицы мутаций пшеницы убрана возможность мутировать её в рис и овес (они и так в свободном доступе, плюс поступали жалобы от ботаников, что данная мутация не нужна в принципе).

![image](https://github.com/Lemirda/space-station-14/assets/160354560/c5148e44-68f9-4ebb-851e-891bf083e252)

2024-04-29 06:25 UTC, Lemirda requested changes

2024-04-29 06:25 UTC, Lemirda commented on Resources/Prototypes/Hydroponics/seeds.yml
> +    meatwheat: #A-13 MeatWheatseed
fix #A-13 MeatWheatseed пояснение в #58

2024-04-29 15:07 UTC, Dalexiandr commented on Resources/Prototypes/Hydroponics/seeds.yml
> +    meatwheat: #A-13 MeatWheatseed
> fix #A-13 MeatWheatseed пояснение в #58

Сделано, проверяй

2024-04-30 12:44 UTC, Lemirda approved these changes
*бумп*

2024-04-30 12:44 UTC, merged