WIP!!! ПР №4 Плюшемат и плюшки
Lemirda/space-station-14 pull request #58
Opened 2024-04-28 11:08 UTC by Dalexiandr

**Проверки**
- [x] Ознакомиться с исходниками
- [ ] Добавить плюшемат
- [ ] Обратиться в РП отдел и к спрайтерам
- [ ] Добавить плюшемат и плюшки
- [ ] Добавить дополнительные плюшки и скорректировать косяки

**Изменения для игроков**
:cl: EvilBug
- add: Добавлен автомат по раздаче плюшевых игрушек - ОбниМат
- add: Добавлены плюшки художника, селекционера, унати, кобольда, кадета, авантюриста, каргонианки и ученой (за спрайты спасибо SadBrat3, s6766, Gehok)

**Изменения для разработчиков**

:cl: EvilBug
- WIP

2024-04-28 14:00 UTC, Lemirda commented
Добавьте автомат в список возможных покупок для карго

2024-04-28 14:01 UTC, Lemirda requested changes
^ this

2024-04-28 17:25 UTC, Dalexiandr commented
> ^ this

Сделал.
Жду спрайтеров, для доделки и правок спрайтов.

2024-04-29 06:24 UTC, Lemirda requested changes
Надо бы добавить в автомат не персональных игрушек (типо не сэдбрата и не меня(потому что вся станция в стонах будет), а типо каких нибудь там плюшевых мишек я хз))

2024-04-29 14:57 UTC, Dalexiandr commented
> Надо бы добавить в автомат не персональных игрушек (типо не сэдбрата и не меня(потому что вся станция в стонах будет), а типо каких нибудь там плюшевых мишек((если у нас такие есть)я хз))

Сделано, проверяй.

2024-04-30 13:31 UTC, Lemirda requested changes
Start to work!

2024-04-30 13:31 UTC, Lemirda commented on Resources/Prototypes/Andromeda/Evil Prototype's/plushiedrobe.yml
> +  name: обнимат
ОбниМат

2024-04-30 13:31 UTC, Lemirda commented on Resources/Prototypes/Andromeda/Evil Prototype's/plushiedrobe.yml
> +  description: Если долго всматриваться в нашу плюшемягкую бездну, можно сгинуть в ней... От умиления!
```suggestion
  description: Если долго всматриваться в эту плюше-мягкую бездну, то можно сгибнуть от умиления!
```

2024-04-30 13:31 UTC, Lemirda commented on Resources/Prototypes/Andromeda/Evil Prototype's/plushiedrobe.yml
> +    - Подходят для шуточной драки!
```suggestion
    - Подходят для не шуточной драки!
```

2024-04-30 13:31 UTC, Lemirda commented on Resources/Prototypes/Andromeda/Evil Prototype's/plushiedrobe.yml
> +    - Лучший друг для сна!
```suggestion
    - Лучший друг или лучшая подруга для сна!
```

2024-04-30 13:31 UTC, Lemirda commented on Resources/Prototypes/Andromeda/Evil Prototype's/plushiedrobe.yml
> +    - Собери их всех!
```suggestion
    - Вы должны их взять лишь потому что их можно жмякать!
```

2024-04-30 13:31 UTC, Lemirda commented on Resources/Prototypes/Andromeda/Evil Prototype's/plushiedrobe.yml
> +    - Порадуйте свою любовь!
```suggestion
    - Порадуйте других людей этой умилительной плюшевой куклой!
```

2024-04-30 13:31 UTC, Lemirda commented on Resources/Prototypes/Andromeda/Evil Prototype's/plushiedrobe.yml
> +    - Можно и смотреть, и лапать!
```suggestion
    - Смотрите и лапайте!
```

2024-04-30 13:31 UTC, Lemirda commented on Resources/Prototypes/Andromeda/Evil Prototype's/plushiedrobe.yml
> +    - Завораживающе милы!
```suggestion
    - Смотрите не умрите от милоты!
```

2024-04-30 13:31 UTC, Lemirda commented on Resources/Prototypes/Andromeda/Evil Prototype's/plushiedrobe.yml
> +    - Слышали их крик?
```suggestion
    - Слышали их стоны?
```

2024-04-30 13:31 UTC, Lemirda commented on Resources/Prototypes/Andromeda/Evil Prototype's/plushiedrobe.yml
> +    - Наши игрушки на девяносто процентов состоят из доброты и на десять - из плутония! ... Шутка!
```suggestion
    - Наши игрушки на девяносто процентов состоят из доброты и на десять - из плутония!... Наверное.
```

2024-04-30 13:31 UTC, Lemirda commented on Resources/Prototypes/Andromeda/Evil Prototype's/plushiedrobe.yml
> +    - И никаких мстительных духов внутри!
```suggestion
    - Никаких мстительных духов внутри плюшевки!
```

2024-04-30 13:31 UTC, Lemirda commented on Resources/Prototypes/Andromeda/Evil Prototype's/plushiedrobe.yml
> +    - Мягче только стены моей комнаты!
```suggestion
    - Мягче только стены комнаты!
```

2024-04-30 13:31 UTC, Lemirda commented on Resources/Prototypes/Andromeda/Evil Prototype's/plushiedrobe.yml
> +    - Не отрывайте им головы!
```suggestion

```

2024-04-30 13:31 UTC, Lemirda commented on Resources/Prototypes/Catalog/Cargo/cargo_service.yml
> +  cost: 2000
```suggestion
  cost: 8000
```

2024-04-30 15:14 UTC, Dalexiandr commented on Resources/Prototypes/Catalog/Cargo/cargo_service.yml
> +  cost: 2000
> 

Все исправлено

2024-04-30 15:48 UTC, Lemirda requested changes

2024-04-30 15:48 UTC, Lemirda commented on Resources/Prototypes/Andromeda/Evil Prototype's/plushiedrobe.yml
> +  description: Если долго всматриваться в нашу плюше-мягкую бездну, то можно сгибнуть от умиления!
```suggestion
  description: Если долго всматриваться в эту плюше-мягкую бездну, то можно сгибнуть от умиления!
```

2024-04-30 15:48 UTC, Lemirda commented on Resources/Textures/Andromeda/Lemird/plushielemird.rsi/meta.json
> +    },
Что это ха хуйня?

2024-04-30 15:48 UTC, Lemirda commented on Resources/Textures/Andromeda/Lemird/plushielemirdschoolgirl.rsi/meta.json
> +    },
И это тоже, что за хуйня? Какого хуя оно тут?

2024-04-30 16:04 UTC, Lemirda requested changes

2024-04-30 16:04 UTC, Lemirda commented on Resources/Prototypes/Andromeda/Evil Prototype's/plushies.yml
> +  name: плюшевый кобольд
Именная игрушка?????

2024-04-30 16:27 UTC, Lemirda requested changes

2024-04-30 16:27 UTC, Lemirda commented on Resources/Prototypes/Andromeda/Evil Prototype's/plushiedrobe.yml
> +  description: Если долго всматриваться в эту плюше-мягкую бездну, то можно сгибнуть от умиления!
Суффикс!!!!!

2024-04-30 16:31 UTC, Lemirda requested changes

2024-04-30 16:31 UTC, Lemirda commented on Resources/Prototypes/Andromeda/Evil Prototype's/plushiedrobe.yml
> +  id: HugsDrobe
VendingMachinePlushieToys

2024-04-30 16:52 UTC, Dalexiandr commented on Resources/Prototypes/Andromeda/Evil Prototype's/plushiedrobe.yml
> +  id: HugsDrobe
> VendingMachinePlushieToys

Исправлено везде айдишник

2024-04-30 17:42 UTC, closed without merging