ПР №5 Плюшевая Лемирд (перенос на голове)
Lemirda/space-station-14 pull request #60
Opened 2024-04-28 11:40 UTC by Dalexiandr

**Проверки**
- [x] Получить от спрайтеров обновленный спрайт плюшевой Лемирд
- [ ] Внести правки в код

**Изменения для игроков**
:cl: EvilBug
- add: Добавлена возможность переноса плюшевой игрушки Лемирд (обычная версия и школьница) на голове.

**Изменения для разработчиков**

:cl: EvilBug
- add: Добавлена возможность переноса плюшевой игрушки Лемирд (обычная версия и школьница) на голове.
Обновлен код, и правки в метафайлы, плюс дополнительные спрайты.

2024-04-28 16:07 UTC, Lemirda requested changes

2024-04-28 16:07 UTC, Lemirda commented on Resources/Prototypes/Andromeda/Lemird Prototype's/schoolgirllemird.yml
> +    - HEAD
Сделай лучше не шее. Она же не на голове сидит

2024-04-28 17:23 UTC, Dalexiandr commented on Resources/Prototypes/Andromeda/Lemird Prototype's/schoolgirllemird.yml
> +    - HEAD
Есть проблема - шапка наезжает.
Предлагаю оставить в слоте шапки, а не побрякушки.

![image](https://github.com/Lemirda/space-station-14/assets/160354560/abec9885-acac-46a2-9e18-0cd0856db0c7)

2024-04-28 17:40 UTC, Dalexiandr commented on Resources/Prototypes/Andromeda/Lemird Prototype's/schoolgirllemird.yml
> +    - HEAD
Вернул голову

2024-04-29 14:44 UTC, Lemirda approved these changes

2024-04-30 13:43 UTC, merged