ПР №6 - плант-о-мат
Lemirda/space-station-14 pull request #61
Opened 2024-04-28 12:03 UTC by Dalexiandr

**Проверки**
- [x] Ознакомиться с исходными данными
- [ ] Обратиться к спрайтерам за перерисовкой
- [ ] Переписать код и добавить сюрприз

**Изменения для игроков**
:cl: EvilBug
- add: Добавлен раздатчик комнатных растений с маааленьким сюрпризом.

**Изменения для разработчиков**

:cl: EvilBug
- add: Добавлен раздатчик комнатных растений, плюс дополнительно прописал ему возможность быть ЕМАГнутым для получения 3х подозрительных растений (сделал сам на основе артефактов)

2024-04-28 16:08 UTC, Lemirda requested changes
Тоже самое, сделай доступ к покупке в карго сам автомат

2024-04-28 17:25 UTC, Dalexiandr commented
> Тоже самое, сделай доступ к покупке в карго сам автомат

Сделал

2024-04-29 06:21 UTC, Lemirda requested changes

2024-04-29 06:21 UTC, Lemirda commented on Resources/Prototypes/Catalog/Cargo/cargo_service.yml
> +- type: cargoProduct # А-13 Плант-О-Мат
Так не пойдёт, указывается именно так:
#А-13 Плант-О-Ма start
*весь код*
#А-13 Плант-О-Ма end
А # А-13 Плант-О-Мат указывается если сообщение одно(именно на него типо показывает:
*вставленный компонент контейнера в плюшевую игрушку от оффов* #А-13 Плюшевая пизда

2024-04-29 15:01 UTC, Dalexiandr commented on Resources/Prototypes/Catalog/Cargo/cargo_service.yml
> +- type: cargoProduct # А-13 Плант-О-Мат
> Так не пойдёт, указывается именно так: #А-13 Плант-О-Ма start _весь код_ #А-13 Плант-О-Ма end А # А-13 Плант-О-Мат указывается если сообщение одно(именно на него типо показывает: _вставленный компонент контейнера в плюшевую игрушку от оффов_ #А-13 Плюшевая пизда

Сделано, проверяй

2024-04-30 13:43 UTC, Lemirda requested changes

2024-04-30 13:43 UTC, Lemirda commented on Resources/Prototypes/Catalog/Cargo/cargo_service.yml
> +  cost: 1500
```suggestion
  cost: 6500
```

2024-04-30 15:14 UTC, Dalexiandr commented on Resources/Prototypes/Catalog/Cargo/cargo_service.yml
> +  cost: 1500
> 

Исправлено

2024-04-30 16:17 UTC, Lemirda approved these changes

2024-04-30 16:17 UTC, merged