ПР №8 Взрывные штучки
Lemirda/space-station-14 pull request #78
Opened 2024-05-04 13:51 UTC by Dalexiandr

**Проверки**
- [ ] Заспавнить FunniPill / FunniPillCanister и убедиться что все работает
- [ ] Заспавнить ClosetMaintenanceFilledRandom / ClosetWallMaintenanceFilledRandom и убедиться что все работает

**Изменения для игроков**
:cl:
- add: В игру добавлены таблетки и таблеточницы с афродизиаком, их стоит искать в технических шкафах.

**Изменения для разработчиков**
:cl:
- add: Добавлена ложная таблетка с афродизиаком. Сделал её похожей на существующую. Состав - 10 калия и 10 уксуса. Добавил таблетки и таблеточницы в спавн шкафов в техах (технических) с шансом 10% таблеточница и 20% таблетка.

2024-05-04 14:33 UTC, Lemirda commented
А чё как мало

2024-05-04 14:47 UTC, Dalexiandr commented
> А чё как мало

Ответь в ЛС наконец.

2024-05-06 13:49 UTC, Lemirda requested changes

2024-05-06 13:49 UTC, Lemirda commented on Resources/Prototypes/Andromeda/Evil Prototype's/funnipills.yml
> +  name: Афродизиак
с маленькой

2024-05-06 17:18 UTC, Dalexiandr commented
Исправил заголовок и немного поправил рандом.
Жду проверки.

2024-05-06 18:49 UTC, merged